environment:
  password:
    secure: f9xXcpXZkJpQhtqSdhI45A==	
  matrix:  
    - python: 27
    - python: 34
    - python: 35
os: Visual Studio 2013
platform:
  - x86
  - x64
install:
  - "SET PATH=C:\\Python%PYTHON%;c:\\Python%PYTHON%\\scripts;%PATH%"
  - echo "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64 > "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\amd64\vcvars64.bat"
  - python setup.py install  
build: false
test_script:
  - python testrun.py
on_success:
  - echo Build succesful!
deploy_script:
  - echo [distutils]                                  > %USERPROFILE%\\.pypirc
  - echo index-servers =                             >> %USERPROFILE%\\.pypirc
  - echo     pypi                                    >> %USERPROFILE%\\.pypirc
  - echo [pypi]                                      >> %USERPROFILE%\\.pypirc
  - echo repository=https://pypi.python.org/pypi     >> %USERPROFILE%\\.pypirc
  - echo username=mattandahalfew                     >> %USERPROFILE%\\.pypirc
  - echo password=%password%                         >> %USERPROFILE%\\.pypirc
  - set HOME=%USERPROFILE%
  - pip install wheel twine
  - python setup.py sdist bdist_wheel
  - twine upload dist/*
deploy : on